// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by "modeldecoder/generator". DO NOT EDIT.

package rumv3

import (
	"encoding/json"
	"fmt"
	"regexp"
	"unicode/utf8"
)

var (
	patternAlphaNumericExtRegexp = regexp.MustCompile(patternAlphaNumericExt)
)

func (val *metadataRoot) IsSet() bool {
	return val.Metadata.IsSet()
}

func (val *metadataRoot) validate() error {
	if val.Metadata.IsSet() {
		if err := val.Metadata.validate(); err != nil {
			return fmt.Errorf("m: %w", err)
		}
	}
	if !val.Metadata.IsSet() {
		return fmt.Errorf("'m' required")
	}
	return nil
}

func (val *metadataRoot) processNestedSource() error {
	if err := val.Metadata.processNestedSource(); err != nil {
		return fmt.Errorf("m: %w", err)
	}
	return nil
}

func (val *metadata) IsSet() bool {
	return (len(val.Labels) > 0) || val.Service.IsSet() || val.User.IsSet() || val.Network.IsSet()
}

func (val *metadata) validate() error {
	for k, v := range val.Labels {
		switch t := v.(type) {
		case nil:
		case string:
			if utf8.RuneCountInString(t) > 1024 {
				return fmt.Errorf("'l': validation rule 'maxLengthVals(1024)' violated")
			}
		case bool:
		case json.Number:
		default:
			return fmt.Errorf("'l': validation rule 'inputTypesVals(string;bool;number)' violated for key %s", k)
		}
	}
	if val.Service.IsSet() {
		if err := val.Service.validate(); err != nil {
			return fmt.Errorf("se: %w", err)
		}
	}
	if !val.Service.IsSet() {
		return fmt.Errorf("'se' required")
	}
	if val.User.IsSet() {
		if err := val.User.validate(); err != nil {
			return fmt.Errorf("u: %w", err)
		}
	}
	if val.Network.IsSet() {
		if err := val.Network.validate(); err != nil {
			return fmt.Errorf("n: %w", err)
		}
	}
	return nil
}

func (val *metadata) processNestedSource() error {
	if err := val.Service.processNestedSource(); err != nil {
		return fmt.Errorf("se: %w", err)
	}
	if err := val.User.processNestedSource(); err != nil {
		return fmt.Errorf("u: %w", err)
	}
	if err := val.Network.processNestedSource(); err != nil {
		return fmt.Errorf("n: %w", err)
	}
	return nil
}

func (val *metadataService) IsSet() bool {
	return val.Agent.IsSet() || val.Environment.IsSet() || val.Framework.IsSet() || val.Language.IsSet() || val.Name.IsSet() || val.Runtime.IsSet() || val.Version.IsSet()
}

func (val *metadataService) validate() error {
	if val.Agent.IsSet() {
		if err := val.Agent.validate(); err != nil {
			return fmt.Errorf("a: %w", err)
		}
	}
	if !val.Agent.IsSet() {
		return fmt.Errorf("'a' required")
	}
	if val.Environment.IsSet() && utf8.RuneCountInString(val.Environment.Val) > 1024 {
		return fmt.Errorf("'en': validation rule 'maxLength(1024)' violated")
	}
	if val.Framework.IsSet() {
		if err := val.Framework.validate(); err != nil {
			return fmt.Errorf("fw: %w", err)
		}
	}
	if val.Language.IsSet() {
		if err := val.Language.validate(); err != nil {
			return fmt.Errorf("la: %w", err)
		}
	}
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) < 1 {
		return fmt.Errorf("'n': validation rule 'minLength(1)' violated")
	}
	if val.Name.Val != "" && !patternAlphaNumericExtRegexp.MatchString(val.Name.Val) {
		return fmt.Errorf("'n': validation rule 'pattern(patternAlphaNumericExt)' violated")
	}
	if !val.Name.IsSet() {
		return fmt.Errorf("'n' required")
	}
	if val.Runtime.IsSet() {
		if err := val.Runtime.validate(); err != nil {
			return fmt.Errorf("ru: %w", err)
		}
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *metadataService) processNestedSource() error {
	if err := val.Agent.processNestedSource(); err != nil {
		return fmt.Errorf("a: %w", err)
	}
	if err := val.Framework.processNestedSource(); err != nil {
		return fmt.Errorf("fw: %w", err)
	}
	if err := val.Language.processNestedSource(); err != nil {
		return fmt.Errorf("la: %w", err)
	}
	if err := val.Runtime.processNestedSource(); err != nil {
		return fmt.Errorf("ru: %w", err)
	}
	return nil
}

func (val *metadataServiceAgent) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *metadataServiceAgent) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) < 1 {
		return fmt.Errorf("'n': validation rule 'minLength(1)' violated")
	}
	if !val.Name.IsSet() {
		return fmt.Errorf("'n' required")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	if !val.Version.IsSet() {
		return fmt.Errorf("'ve' required")
	}
	return nil
}

func (val *metadataServiceAgent) processNestedSource() error {
	return nil
}

func (val *metadataServiceFramework) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *metadataServiceFramework) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *metadataServiceFramework) processNestedSource() error {
	return nil
}

func (val *metadataServiceLanguage) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *metadataServiceLanguage) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if !val.Name.IsSet() {
		return fmt.Errorf("'n' required")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *metadataServiceLanguage) processNestedSource() error {
	return nil
}

func (val *metadataServiceRuntime) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *metadataServiceRuntime) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if !val.Name.IsSet() {
		return fmt.Errorf("'n' required")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	if !val.Version.IsSet() {
		return fmt.Errorf("'ve' required")
	}
	return nil
}

func (val *metadataServiceRuntime) processNestedSource() error {
	return nil
}

func (val *user) IsSet() bool {
	return val.Domain.IsSet() || val.ID.IsSet() || val.Email.IsSet() || val.Name.IsSet()
}

func (val *user) validate() error {
	if val.Domain.IsSet() && utf8.RuneCountInString(val.Domain.Val) > 1024 {
		return fmt.Errorf("'ud': validation rule 'maxLength(1024)' violated")
	}
	switch t := val.ID.Val.(type) {
	case string:
		if utf8.RuneCountInString(t) > 1024 {
			return fmt.Errorf("'id': validation rule 'maxLength(1024)' violated")
		}
	case int:
	case json.Number:
		if _, err := t.Int64(); err != nil {
			return fmt.Errorf("'id': validation rule 'inputTypes(string;int)' violated")
		}
	case nil:
	default:
		return fmt.Errorf("'id': validation rule 'inputTypes(string;int)' violated ")
	}
	if val.Email.IsSet() && utf8.RuneCountInString(val.Email.Val) > 1024 {
		return fmt.Errorf("'em': validation rule 'maxLength(1024)' violated")
	}
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'un': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *user) processNestedSource() error {
	return nil
}

func (val *network) IsSet() bool {
	return val.Connection.IsSet()
}

func (val *network) validate() error {
	if val.Connection.IsSet() {
		if err := val.Connection.validate(); err != nil {
			return fmt.Errorf("c: %w", err)
		}
	}
	return nil
}

func (val *network) processNestedSource() error {
	if err := val.Connection.processNestedSource(); err != nil {
		return fmt.Errorf("c: %w", err)
	}
	return nil
}

func (val *networkConnection) IsSet() bool {
	return val.Type.IsSet()
}

func (val *networkConnection) validate() error {
	if val.Type.IsSet() && utf8.RuneCountInString(val.Type.Val) > 1024 {
		return fmt.Errorf("'t': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *networkConnection) processNestedSource() error {
	return nil
}

func (val *errorRoot) IsSet() bool {
	return val.Error.IsSet()
}

func (val *errorRoot) validate() error {
	if val.Error.IsSet() {
		if err := val.Error.validate(); err != nil {
			return fmt.Errorf("e: %w", err)
		}
	}
	if !val.Error.IsSet() {
		return fmt.Errorf("'e' required")
	}
	return nil
}

func (val *errorRoot) processNestedSource() error {
	if err := val.Error.processNestedSource(); err != nil {
		return fmt.Errorf("e: %w", err)
	}
	return nil
}

func (val *errorEvent) IsSet() bool {
	return val.Timestamp.IsSet() || val.Log.IsSet() || val.Culprit.IsSet() || val.ID.IsSet() || val.ParentID.IsSet() || val.TraceID.IsSet() || val.TransactionID.IsSet() || val.Exception.IsSet() || val.Transaction.IsSet() || val.Context.IsSet()
}

func (val *errorEvent) validate() error {
	if !val.Exception.IsSet() && !val.Log.IsSet() {
		return fmt.Errorf("requires at least one of the fields 'ex;log'")
	}
	if val.Log.IsSet() {
		if err := val.Log.validate(); err != nil {
			return fmt.Errorf("log: %w", err)
		}
	}
	if val.Culprit.IsSet() && utf8.RuneCountInString(val.Culprit.Val) > 1024 {
		return fmt.Errorf("'cl': validation rule 'maxLength(1024)' violated")
	}
	if val.ID.IsSet() && utf8.RuneCountInString(val.ID.Val) > 1024 {
		return fmt.Errorf("'id': validation rule 'maxLength(1024)' violated")
	}
	if !val.ID.IsSet() {
		return fmt.Errorf("'id' required")
	}
	if val.ParentID.IsSet() && utf8.RuneCountInString(val.ParentID.Val) > 1024 {
		return fmt.Errorf("'pid': validation rule 'maxLength(1024)' violated")
	}
	if !val.ParentID.IsSet() {
		if val.TransactionID.IsSet() {
			return fmt.Errorf("'pid' required when 'xid' is set")
		}
		if val.TraceID.IsSet() {
			return fmt.Errorf("'pid' required when 'tid' is set")
		}
	}
	if val.TraceID.IsSet() && utf8.RuneCountInString(val.TraceID.Val) > 1024 {
		return fmt.Errorf("'tid': validation rule 'maxLength(1024)' violated")
	}
	if !val.TraceID.IsSet() {
		if val.TransactionID.IsSet() {
			return fmt.Errorf("'tid' required when 'xid' is set")
		}
		if val.ParentID.IsSet() {
			return fmt.Errorf("'tid' required when 'pid' is set")
		}
	}
	if val.TransactionID.IsSet() && utf8.RuneCountInString(val.TransactionID.Val) > 1024 {
		return fmt.Errorf("'xid': validation rule 'maxLength(1024)' violated")
	}
	if val.Exception.IsSet() {
		if err := val.Exception.validate(); err != nil {
			return fmt.Errorf("ex: %w", err)
		}
	}
	if val.Transaction.IsSet() {
		if err := val.Transaction.validate(); err != nil {
			return fmt.Errorf("x: %w", err)
		}
	}
	if val.Context.IsSet() {
		if err := val.Context.validate(); err != nil {
			return fmt.Errorf("c: %w", err)
		}
	}
	return nil
}

func (val *errorEvent) processNestedSource() error {
	if err := val.Log.processNestedSource(); err != nil {
		return fmt.Errorf("log: %w", err)
	}
	if err := val.Exception.processNestedSource(); err != nil {
		return fmt.Errorf("ex: %w", err)
	}
	if err := val.Transaction.processNestedSource(); err != nil {
		return fmt.Errorf("x: %w", err)
	}
	if err := val.Context.processNestedSource(); err != nil {
		return fmt.Errorf("c: %w", err)
	}
	return nil
}

func (val *errorLog) IsSet() bool {
	return val.Level.IsSet() || val.LoggerName.IsSet() || val.Message.IsSet() || val.ParamMessage.IsSet() || (len(val.Stacktrace) > 0)
}

func (val *errorLog) validate() error {
	if val.Level.IsSet() && utf8.RuneCountInString(val.Level.Val) > 1024 {
		return fmt.Errorf("'lv': validation rule 'maxLength(1024)' violated")
	}
	if val.LoggerName.IsSet() && utf8.RuneCountInString(val.LoggerName.Val) > 1024 {
		return fmt.Errorf("'ln': validation rule 'maxLength(1024)' violated")
	}
	if !val.Message.IsSet() {
		return fmt.Errorf("'mg' required")
	}
	if val.ParamMessage.IsSet() && utf8.RuneCountInString(val.ParamMessage.Val) > 1024 {
		return fmt.Errorf("'pmg': validation rule 'maxLength(1024)' violated")
	}
	for _, elem := range val.Stacktrace {
		if !elem.IsSet() {
			return fmt.Errorf("st slice element required")
		}
		if err := elem.validate(); err != nil {
			return fmt.Errorf("st: %w", err)
		}
	}
	return nil
}

func (val *errorLog) processNestedSource() error {
	return nil
}

func (val *stacktraceFrame) IsSet() bool {
	return val.AbsPath.IsSet() || val.Classname.IsSet() || val.ContextLine.IsSet() || val.Filename.IsSet() || val.Function.IsSet() || val.Module.IsSet() || (len(val.PostContext) > 0) || (len(val.PreContext) > 0) || val.ColumnNumber.IsSet() || val.LineNumber.IsSet()
}

func (val *stacktraceFrame) validate() error {
	if !val.Filename.IsSet() {
		return fmt.Errorf("'f' required")
	}
	return nil
}

func (val *stacktraceFrame) processNestedSource() error {
	return nil
}

func (val *errorException) IsSet() bool {
	return (len(val.Attributes) > 0) || val.Code.IsSet() || (len(val.Cause) > 0) || val.Message.IsSet() || val.Module.IsSet() || (len(val.Stacktrace) > 0) || val.Type.IsSet() || val.Handled.IsSet()
}

func (val *errorException) validate() error {
	if !val.Message.IsSet() && !val.Type.IsSet() {
		return fmt.Errorf("requires at least one of the fields 'mg;t'")
	}
	switch t := val.Code.Val.(type) {
	case string:
		if utf8.RuneCountInString(t) > 1024 {
			return fmt.Errorf("'cd': validation rule 'maxLength(1024)' violated")
		}
	case int:
	case json.Number:
		if _, err := t.Int64(); err != nil {
			return fmt.Errorf("'cd': validation rule 'inputTypes(string;int)' violated")
		}
	case nil:
	default:
		return fmt.Errorf("'cd': validation rule 'inputTypes(string;int)' violated ")
	}
	for _, elem := range val.Cause {
		if !elem.IsSet() {
			return fmt.Errorf("ca slice element required")
		}
		if err := elem.validate(); err != nil {
			return fmt.Errorf("ca: %w", err)
		}
	}
	if val.Module.IsSet() && utf8.RuneCountInString(val.Module.Val) > 1024 {
		return fmt.Errorf("'mo': validation rule 'maxLength(1024)' violated")
	}
	for _, elem := range val.Stacktrace {
		if !elem.IsSet() {
			return fmt.Errorf("st slice element required")
		}
		if err := elem.validate(); err != nil {
			return fmt.Errorf("st: %w", err)
		}
	}
	if val.Type.IsSet() && utf8.RuneCountInString(val.Type.Val) > 1024 {
		return fmt.Errorf("'t': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *errorException) processNestedSource() error {
	return nil
}

func (val *errorTransactionRef) IsSet() bool {
	return val.Name.IsSet() || val.Type.IsSet() || val.Sampled.IsSet()
}

func (val *errorTransactionRef) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Type.IsSet() && utf8.RuneCountInString(val.Type.Val) > 1024 {
		return fmt.Errorf("'t': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *errorTransactionRef) processNestedSource() error {
	return nil
}

func (val *context) IsSet() bool {
	return (len(val.Custom) > 0) || (len(val.Tags) > 0) || val.Service.IsSet() || val.User.IsSet() || val.Request.IsSet() || val.Page.IsSet() || val.Response.IsSet()
}

func (val *context) validate() error {
	for k, v := range val.Tags {
		switch t := v.(type) {
		case nil:
		case string:
			if utf8.RuneCountInString(t) > 1024 {
				return fmt.Errorf("'g': validation rule 'maxLengthVals(1024)' violated")
			}
		case bool:
		case json.Number:
		default:
			return fmt.Errorf("'g': validation rule 'inputTypesVals(string;bool;number)' violated for key %s", k)
		}
	}
	if val.Service.IsSet() {
		if err := val.Service.validate(); err != nil {
			return fmt.Errorf("se: %w", err)
		}
	}
	if val.User.IsSet() {
		if err := val.User.validate(); err != nil {
			return fmt.Errorf("u: %w", err)
		}
	}
	if val.Request.IsSet() {
		if err := val.Request.validate(); err != nil {
			return fmt.Errorf("q: %w", err)
		}
	}
	if val.Page.IsSet() {
		if err := val.Page.validate(); err != nil {
			return fmt.Errorf("p: %w", err)
		}
	}
	if val.Response.IsSet() {
		if err := val.Response.validate(); err != nil {
			return fmt.Errorf("r: %w", err)
		}
	}
	return nil
}

func (val *context) processNestedSource() error {
	if err := val.Service.processNestedSource(); err != nil {
		return fmt.Errorf("se: %w", err)
	}
	if err := val.User.processNestedSource(); err != nil {
		return fmt.Errorf("u: %w", err)
	}
	if err := val.Request.processNestedSource(); err != nil {
		return fmt.Errorf("q: %w", err)
	}
	if err := val.Page.processNestedSource(); err != nil {
		return fmt.Errorf("p: %w", err)
	}
	if err := val.Response.processNestedSource(); err != nil {
		return fmt.Errorf("r: %w", err)
	}
	return nil
}

func (val *contextService) IsSet() bool {
	return val.Agent.IsSet() || val.Environment.IsSet() || val.Framework.IsSet() || val.Language.IsSet() || val.Name.IsSet() || val.Runtime.IsSet() || val.Version.IsSet()
}

func (val *contextService) validate() error {
	if val.Agent.IsSet() {
		if err := val.Agent.validate(); err != nil {
			return fmt.Errorf("a: %w", err)
		}
	}
	if val.Environment.IsSet() && utf8.RuneCountInString(val.Environment.Val) > 1024 {
		return fmt.Errorf("'en': validation rule 'maxLength(1024)' violated")
	}
	if val.Framework.IsSet() {
		if err := val.Framework.validate(); err != nil {
			return fmt.Errorf("fw: %w", err)
		}
	}
	if val.Language.IsSet() {
		if err := val.Language.validate(); err != nil {
			return fmt.Errorf("la: %w", err)
		}
	}
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Name.Val != "" && !patternAlphaNumericExtRegexp.MatchString(val.Name.Val) {
		return fmt.Errorf("'n': validation rule 'pattern(patternAlphaNumericExt)' violated")
	}
	if val.Runtime.IsSet() {
		if err := val.Runtime.validate(); err != nil {
			return fmt.Errorf("ru: %w", err)
		}
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *contextService) processNestedSource() error {
	if err := val.Agent.processNestedSource(); err != nil {
		return fmt.Errorf("a: %w", err)
	}
	if err := val.Framework.processNestedSource(); err != nil {
		return fmt.Errorf("fw: %w", err)
	}
	if err := val.Language.processNestedSource(); err != nil {
		return fmt.Errorf("la: %w", err)
	}
	if err := val.Runtime.processNestedSource(); err != nil {
		return fmt.Errorf("ru: %w", err)
	}
	return nil
}

func (val *contextServiceAgent) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *contextServiceAgent) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *contextServiceAgent) processNestedSource() error {
	return nil
}

func (val *contextServiceFramework) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *contextServiceFramework) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *contextServiceFramework) processNestedSource() error {
	return nil
}

func (val *contextServiceLanguage) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *contextServiceLanguage) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *contextServiceLanguage) processNestedSource() error {
	return nil
}

func (val *contextServiceRuntime) IsSet() bool {
	return val.Name.IsSet() || val.Version.IsSet()
}

func (val *contextServiceRuntime) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Version.IsSet() && utf8.RuneCountInString(val.Version.Val) > 1024 {
		return fmt.Errorf("'ve': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *contextServiceRuntime) processNestedSource() error {
	return nil
}

func (val *contextRequest) IsSet() bool {
	return (len(val.Env) > 0) || val.Headers.IsSet() || val.HTTPVersion.IsSet() || val.Method.IsSet()
}

func (val *contextRequest) validate() error {
	if val.HTTPVersion.IsSet() && utf8.RuneCountInString(val.HTTPVersion.Val) > 1024 {
		return fmt.Errorf("'hve': validation rule 'maxLength(1024)' violated")
	}
	if val.Method.IsSet() && utf8.RuneCountInString(val.Method.Val) > 1024 {
		return fmt.Errorf("'mt': validation rule 'maxLength(1024)' violated")
	}
	if !val.Method.IsSet() {
		return fmt.Errorf("'mt' required")
	}
	return nil
}

func (val *contextRequest) processNestedSource() error {
	return nil
}

func (val *contextPage) IsSet() bool {
	return val.Referer.IsSet() || val.URL.IsSet()
}

func (val *contextPage) validate() error {
	return nil
}

func (val *contextPage) processNestedSource() error {
	return nil
}

func (val *contextResponse) IsSet() bool {
	return val.Headers.IsSet() || val.DecodedBodySize.IsSet() || val.EncodedBodySize.IsSet() || val.StatusCode.IsSet() || val.TransferSize.IsSet()
}

func (val *contextResponse) validate() error {
	return nil
}

func (val *contextResponse) processNestedSource() error {
	return nil
}

func (val *transactionRoot) IsSet() bool {
	return val.Transaction.IsSet()
}

func (val *transactionRoot) validate() error {
	if val.Transaction.IsSet() {
		if err := val.Transaction.validate(); err != nil {
			return fmt.Errorf("x: %w", err)
		}
	}
	if !val.Transaction.IsSet() {
		return fmt.Errorf("'x' required")
	}
	return nil
}

func (val *transactionRoot) processNestedSource() error {
	if err := val.Transaction.processNestedSource(); err != nil {
		return fmt.Errorf("x: %w", err)
	}
	return nil
}

func (val *transaction) IsSet() bool {
	return val.Marks.IsSet() || val.TraceID.IsSet() || val.Type.IsSet() || (len(val.Spans) > 0) || (len(val.Metricsets) > 0) || val.Result.IsSet() || val.ID.IsSet() || val.Name.IsSet() || val.Outcome.IsSet() || val.ParentID.IsSet() || val.Session.IsSet() || val.Context.IsSet() || val.UserExperience.IsSet() || val.SpanCount.IsSet() || val.SampleRate.IsSet() || val.Duration.IsSet() || val.Sampled.IsSet()
}

func (val *transaction) validate() error {
	if val.Marks.IsSet() {
		if err := val.Marks.validate(); err != nil {
			return fmt.Errorf("k: %w", err)
		}
	}
	if val.TraceID.IsSet() && utf8.RuneCountInString(val.TraceID.Val) > 1024 {
		return fmt.Errorf("'tid': validation rule 'maxLength(1024)' violated")
	}
	if !val.TraceID.IsSet() {
		return fmt.Errorf("'tid' required")
	}
	if val.Type.IsSet() && utf8.RuneCountInString(val.Type.Val) > 1024 {
		return fmt.Errorf("'t': validation rule 'maxLength(1024)' violated")
	}
	if !val.Type.IsSet() {
		return fmt.Errorf("'t' required")
	}
	for _, elem := range val.Spans {
		if !elem.IsSet() {
			return fmt.Errorf("y slice element required")
		}
		if err := elem.validate(); err != nil {
			return fmt.Errorf("y: %w", err)
		}
	}
	for _, elem := range val.Metricsets {
		if !elem.IsSet() {
			return fmt.Errorf("me slice element required")
		}
		if err := elem.validate(); err != nil {
			return fmt.Errorf("me: %w", err)
		}
	}
	if val.Result.IsSet() && utf8.RuneCountInString(val.Result.Val) > 1024 {
		return fmt.Errorf("'rt': validation rule 'maxLength(1024)' violated")
	}
	if val.ID.IsSet() && utf8.RuneCountInString(val.ID.Val) > 1024 {
		return fmt.Errorf("'id': validation rule 'maxLength(1024)' violated")
	}
	if !val.ID.IsSet() {
		return fmt.Errorf("'id' required")
	}
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Outcome.Val != "" {
		var matchEnum bool
		for _, s := range enumOutcome {
			if val.Outcome.Val == s {
				matchEnum = true
				break
			}
		}
		if !matchEnum {
			return fmt.Errorf("'o': validation rule 'enum(enumOutcome)' violated")
		}
	}
	if val.ParentID.IsSet() && utf8.RuneCountInString(val.ParentID.Val) > 1024 {
		return fmt.Errorf("'pid': validation rule 'maxLength(1024)' violated")
	}
	if val.Session.IsSet() {
		if err := val.Session.validate(); err != nil {
			return fmt.Errorf("ses: %w", err)
		}
	}
	if val.Context.IsSet() {
		if err := val.Context.validate(); err != nil {
			return fmt.Errorf("c: %w", err)
		}
	}
	if val.UserExperience.IsSet() {
		if err := val.UserExperience.validate(); err != nil {
			return fmt.Errorf("exp: %w", err)
		}
	}
	if val.SpanCount.IsSet() {
		if err := val.SpanCount.validate(); err != nil {
			return fmt.Errorf("yc: %w", err)
		}
	}
	if !val.SpanCount.IsSet() {
		return fmt.Errorf("'yc' required")
	}
	if val.Duration.IsSet() && val.Duration.Val < 0 {
		return fmt.Errorf("'d': validation rule 'min(0)' violated")
	}
	if !val.Duration.IsSet() {
		return fmt.Errorf("'d' required")
	}
	return nil
}

func (val *transaction) processNestedSource() error {
	if err := val.Marks.processNestedSource(); err != nil {
		return fmt.Errorf("k: %w", err)
	}
	if err := val.Session.processNestedSource(); err != nil {
		return fmt.Errorf("ses: %w", err)
	}
	if err := val.Context.processNestedSource(); err != nil {
		return fmt.Errorf("c: %w", err)
	}
	if err := val.UserExperience.processNestedSource(); err != nil {
		return fmt.Errorf("exp: %w", err)
	}
	if err := val.SpanCount.processNestedSource(); err != nil {
		return fmt.Errorf("yc: %w", err)
	}
	return nil
}

func (val *transactionMarks) IsSet() bool {
	return (len(val.Events) > 0)
}

func (val *transactionMarks) validate() error {
	return nil
}

func (val *transactionMarks) processNestedSource() error {
	return nil
}

func (val *transactionMarkEvents) IsSet() bool {
	return (len(val.Measurements) > 0)
}

func (val *transactionMarkEvents) validate() error {
	return nil
}

func (val *transactionMarkEvents) processNestedSource() error {
	return nil
}

func (val *span) IsSet() bool {
	return val.Name.IsSet() || (len(val.Stacktrace) > 0) || val.Type.IsSet() || val.Subtype.IsSet() || val.Action.IsSet() || val.ID.IsSet() || val.Outcome.IsSet() || val.Context.IsSet() || val.ParentIndex.IsSet() || val.SampleRate.IsSet() || val.Start.IsSet() || val.Duration.IsSet() || val.Sync.IsSet()
}

func (val *span) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if !val.Name.IsSet() {
		return fmt.Errorf("'n' required")
	}
	for _, elem := range val.Stacktrace {
		if !elem.IsSet() {
			return fmt.Errorf("st slice element required")
		}
		if err := elem.validate(); err != nil {
			return fmt.Errorf("st: %w", err)
		}
	}
	if val.Type.IsSet() && utf8.RuneCountInString(val.Type.Val) > 1024 {
		return fmt.Errorf("'t': validation rule 'maxLength(1024)' violated")
	}
	if !val.Type.IsSet() {
		return fmt.Errorf("'t' required")
	}
	if val.Subtype.IsSet() && utf8.RuneCountInString(val.Subtype.Val) > 1024 {
		return fmt.Errorf("'su': validation rule 'maxLength(1024)' violated")
	}
	if val.Action.IsSet() && utf8.RuneCountInString(val.Action.Val) > 1024 {
		return fmt.Errorf("'ac': validation rule 'maxLength(1024)' violated")
	}
	if val.ID.IsSet() && utf8.RuneCountInString(val.ID.Val) > 1024 {
		return fmt.Errorf("'id': validation rule 'maxLength(1024)' violated")
	}
	if !val.ID.IsSet() {
		return fmt.Errorf("'id' required")
	}
	if val.Outcome.Val != "" {
		var matchEnum bool
		for _, s := range enumOutcome {
			if val.Outcome.Val == s {
				matchEnum = true
				break
			}
		}
		if !matchEnum {
			return fmt.Errorf("'o': validation rule 'enum(enumOutcome)' violated")
		}
	}
	if val.Context.IsSet() {
		if err := val.Context.validate(); err != nil {
			return fmt.Errorf("c: %w", err)
		}
	}
	if !val.Start.IsSet() {
		return fmt.Errorf("'s' required")
	}
	if val.Duration.IsSet() && val.Duration.Val < 0 {
		return fmt.Errorf("'d': validation rule 'min(0)' violated")
	}
	if !val.Duration.IsSet() {
		return fmt.Errorf("'d' required")
	}
	return nil
}

func (val *span) processNestedSource() error {
	if err := val.Context.processNestedSource(); err != nil {
		return fmt.Errorf("c: %w", err)
	}
	return nil
}

func (val *spanContext) IsSet() bool {
	return (len(val.Tags) > 0) || val.Service.IsSet() || val.Destination.IsSet() || val.HTTP.IsSet()
}

func (val *spanContext) validate() error {
	for k, v := range val.Tags {
		switch t := v.(type) {
		case nil:
		case string:
			if utf8.RuneCountInString(t) > 1024 {
				return fmt.Errorf("'g': validation rule 'maxLengthVals(1024)' violated")
			}
		case bool:
		case json.Number:
		default:
			return fmt.Errorf("'g': validation rule 'inputTypesVals(string;bool;number)' violated for key %s", k)
		}
	}
	if val.Service.IsSet() {
		if err := val.Service.validate(); err != nil {
			return fmt.Errorf("se: %w", err)
		}
	}
	if val.Destination.IsSet() {
		if err := val.Destination.validate(); err != nil {
			return fmt.Errorf("dt: %w", err)
		}
	}
	if val.HTTP.IsSet() {
		if err := val.HTTP.validate(); err != nil {
			return fmt.Errorf("h: %w", err)
		}
	}
	return nil
}

func (val *spanContext) processNestedSource() error {
	if err := val.Service.processNestedSource(); err != nil {
		return fmt.Errorf("se: %w", err)
	}
	if err := val.Destination.processNestedSource(); err != nil {
		return fmt.Errorf("dt: %w", err)
	}
	if err := val.HTTP.processNestedSource(); err != nil {
		return fmt.Errorf("h: %w", err)
	}
	return nil
}

func (val *spanContextService) IsSet() bool {
	return val.Agent.IsSet() || val.Name.IsSet()
}

func (val *spanContextService) validate() error {
	if val.Agent.IsSet() {
		if err := val.Agent.validate(); err != nil {
			return fmt.Errorf("a: %w", err)
		}
	}
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Name.Val != "" && !patternAlphaNumericExtRegexp.MatchString(val.Name.Val) {
		return fmt.Errorf("'n': validation rule 'pattern(patternAlphaNumericExt)' violated")
	}
	return nil
}

func (val *spanContextService) processNestedSource() error {
	if err := val.Agent.processNestedSource(); err != nil {
		return fmt.Errorf("a: %w", err)
	}
	return nil
}

func (val *spanContextDestination) IsSet() bool {
	return val.Service.IsSet() || val.Address.IsSet() || val.Port.IsSet()
}

func (val *spanContextDestination) validate() error {
	if val.Service.IsSet() {
		if err := val.Service.validate(); err != nil {
			return fmt.Errorf("se: %w", err)
		}
	}
	if val.Address.IsSet() && utf8.RuneCountInString(val.Address.Val) > 1024 {
		return fmt.Errorf("'ad': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *spanContextDestination) processNestedSource() error {
	if err := val.Service.processNestedSource(); err != nil {
		return fmt.Errorf("se: %w", err)
	}
	return nil
}

func (val *spanContextDestinationService) IsSet() bool {
	return val.Name.IsSet() || val.Resource.IsSet() || val.Type.IsSet()
}

func (val *spanContextDestinationService) validate() error {
	if val.Name.IsSet() && utf8.RuneCountInString(val.Name.Val) > 1024 {
		return fmt.Errorf("'n': validation rule 'maxLength(1024)' violated")
	}
	if val.Resource.IsSet() && utf8.RuneCountInString(val.Resource.Val) > 1024 {
		return fmt.Errorf("'rc': validation rule 'maxLength(1024)' violated")
	}
	if !val.Resource.IsSet() {
		return fmt.Errorf("'rc' required")
	}
	if val.Type.IsSet() && utf8.RuneCountInString(val.Type.Val) > 1024 {
		return fmt.Errorf("'t': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *spanContextDestinationService) processNestedSource() error {
	return nil
}

func (val *spanContextHTTP) IsSet() bool {
	return val.Method.IsSet() || val.URL.IsSet() || val.Response.IsSet() || val.StatusCode.IsSet()
}

func (val *spanContextHTTP) validate() error {
	if val.Method.IsSet() && utf8.RuneCountInString(val.Method.Val) > 1024 {
		return fmt.Errorf("'mt': validation rule 'maxLength(1024)' violated")
	}
	if val.Response.IsSet() {
		if err := val.Response.validate(); err != nil {
			return fmt.Errorf("r: %w", err)
		}
	}
	return nil
}

func (val *spanContextHTTP) processNestedSource() error {
	if err := val.Response.processNestedSource(); err != nil {
		return fmt.Errorf("r: %w", err)
	}
	return nil
}

func (val *spanContextHTTPResponse) IsSet() bool {
	return val.DecodedBodySize.IsSet() || val.EncodedBodySize.IsSet() || val.TransferSize.IsSet()
}

func (val *spanContextHTTPResponse) validate() error {
	return nil
}

func (val *spanContextHTTPResponse) processNestedSource() error {
	return nil
}

func (val *transactionMetricset) IsSet() bool {
	return val.Span.IsSet() || val.Samples.IsSet()
}

func (val *transactionMetricset) validate() error {
	if val.Span.IsSet() {
		if err := val.Span.validate(); err != nil {
			return fmt.Errorf("y: %w", err)
		}
	}
	if val.Samples.IsSet() {
		if err := val.Samples.validate(); err != nil {
			return fmt.Errorf("sa: %w", err)
		}
	}
	if !val.Samples.IsSet() {
		return fmt.Errorf("'sa' required")
	}
	return nil
}

func (val *transactionMetricset) processNestedSource() error {
	if err := val.Span.processNestedSource(); err != nil {
		return fmt.Errorf("y: %w", err)
	}
	if err := val.Samples.processNestedSource(); err != nil {
		return fmt.Errorf("sa: %w", err)
	}
	return nil
}

func (val *metricsetSpanRef) IsSet() bool {
	return val.Subtype.IsSet() || val.Type.IsSet()
}

func (val *metricsetSpanRef) validate() error {
	if val.Subtype.IsSet() && utf8.RuneCountInString(val.Subtype.Val) > 1024 {
		return fmt.Errorf("'su': validation rule 'maxLength(1024)' violated")
	}
	if val.Type.IsSet() && utf8.RuneCountInString(val.Type.Val) > 1024 {
		return fmt.Errorf("'t': validation rule 'maxLength(1024)' violated")
	}
	return nil
}

func (val *metricsetSpanRef) processNestedSource() error {
	return nil
}

func (val *transactionMetricsetSamples) IsSet() bool {
	return val.SpanSelfTimeCount.IsSet() || val.SpanSelfTimeSum.IsSet()
}

func (val *transactionMetricsetSamples) validate() error {
	if val.SpanSelfTimeCount.IsSet() {
		if err := val.SpanSelfTimeCount.validate(); err != nil {
			return fmt.Errorf("ysc: %w", err)
		}
	}
	if val.SpanSelfTimeSum.IsSet() {
		if err := val.SpanSelfTimeSum.validate(); err != nil {
			return fmt.Errorf("yss: %w", err)
		}
	}
	return nil
}

func (val *transactionMetricsetSamples) processNestedSource() error {
	if err := val.SpanSelfTimeCount.processNestedSource(); err != nil {
		return fmt.Errorf("ysc: %w", err)
	}
	if err := val.SpanSelfTimeSum.processNestedSource(); err != nil {
		return fmt.Errorf("yss: %w", err)
	}
	return nil
}

func (val *metricsetSampleValue) IsSet() bool {
	return val.Value.IsSet()
}

func (val *metricsetSampleValue) validate() error {
	if !val.Value.IsSet() {
		return fmt.Errorf("'v' required")
	}
	return nil
}

func (val *metricsetSampleValue) processNestedSource() error {
	return nil
}

func (val *transactionSession) IsSet() bool {
	return val.ID.IsSet() || val.Sequence.IsSet()
}

func (val *transactionSession) validate() error {
	if !val.ID.IsSet() {
		return fmt.Errorf("'id' required")
	}
	if val.Sequence.IsSet() && val.Sequence.Val < 1 {
		return fmt.Errorf("'seq': validation rule 'min(1)' violated")
	}
	return nil
}

func (val *transactionSession) processNestedSource() error {
	return nil
}

func (val *transactionUserExperience) IsSet() bool {
	return val.CumulativeLayoutShift.IsSet() || val.FirstInputDelay.IsSet() || val.TotalBlockingTime.IsSet() || val.Longtask.IsSet()
}

func (val *transactionUserExperience) validate() error {
	if val.CumulativeLayoutShift.IsSet() && val.CumulativeLayoutShift.Val < 0 {
		return fmt.Errorf("'cls': validation rule 'min(0)' violated")
	}
	if val.FirstInputDelay.IsSet() && val.FirstInputDelay.Val < 0 {
		return fmt.Errorf("'fid': validation rule 'min(0)' violated")
	}
	if val.TotalBlockingTime.IsSet() && val.TotalBlockingTime.Val < 0 {
		return fmt.Errorf("'tbt': validation rule 'min(0)' violated")
	}
	if val.Longtask.IsSet() {
		if err := val.Longtask.validate(); err != nil {
			return fmt.Errorf("lt: %w", err)
		}
	}
	return nil
}

func (val *transactionUserExperience) processNestedSource() error {
	if err := val.Longtask.processNestedSource(); err != nil {
		return fmt.Errorf("lt: %w", err)
	}
	return nil
}

func (val *longtaskMetrics) IsSet() bool {
	return val.Count.IsSet() || val.Max.IsSet() || val.Sum.IsSet()
}

func (val *longtaskMetrics) validate() error {
	if val.Count.IsSet() && val.Count.Val < 0 {
		return fmt.Errorf("'count': validation rule 'min(0)' violated")
	}
	if !val.Count.IsSet() {
		return fmt.Errorf("'count' required")
	}
	if val.Max.IsSet() && val.Max.Val < 0 {
		return fmt.Errorf("'max': validation rule 'min(0)' violated")
	}
	if !val.Max.IsSet() {
		return fmt.Errorf("'max' required")
	}
	if val.Sum.IsSet() && val.Sum.Val < 0 {
		return fmt.Errorf("'sum': validation rule 'min(0)' violated")
	}
	if !val.Sum.IsSet() {
		return fmt.Errorf("'sum' required")
	}
	return nil
}

func (val *longtaskMetrics) processNestedSource() error {
	return nil
}

func (val *transactionSpanCount) IsSet() bool {
	return val.Dropped.IsSet() || val.Started.IsSet()
}

func (val *transactionSpanCount) validate() error {
	if !val.Started.IsSet() {
		return fmt.Errorf("'sd' required")
	}
	return nil
}

func (val *transactionSpanCount) processNestedSource() error {
	return nil
}
