name: Add new issues to the project board

on:
  issues:
    types:
      - opened
      - transferred

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
          permission-organization-projects: write
          permission-issues: read

      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/elastic/projects/1286
          github-token: ${{ steps.get_token.outputs.token }}