// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: apmevent.proto

package modelpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APMEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nanoseconds since epoch
	Timestamp     uint64                        `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Span          *Span                         `protobuf:"bytes,2,opt,name=span,proto3" json:"span,omitempty"`
	NumericLabels map[string]*NumericLabelValue `protobuf:"bytes,3,rep,name=numeric_labels,json=numericLabels,proto3" json:"numeric_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]*LabelValue        `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Transaction   *Transaction                  `protobuf:"bytes,5,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Metricset     *Metricset                    `protobuf:"bytes,6,opt,name=metricset,proto3" json:"metricset,omitempty"`
	Error         *Error                        `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Cloud         *Cloud                        `protobuf:"bytes,8,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Service       *Service                      `protobuf:"bytes,9,opt,name=service,proto3" json:"service,omitempty"`
	Faas          *Faas                         `protobuf:"bytes,10,opt,name=faas,proto3" json:"faas,omitempty"`
	Network       *Network                      `protobuf:"bytes,11,opt,name=network,proto3" json:"network,omitempty"`
	Container     *Container                    `protobuf:"bytes,12,opt,name=container,proto3" json:"container,omitempty"`
	User          *User                         `protobuf:"bytes,13,opt,name=user,proto3" json:"user,omitempty"`
	Device        *Device                       `protobuf:"bytes,14,opt,name=device,proto3" json:"device,omitempty"`
	Kubernetes    *Kubernetes                   `protobuf:"bytes,15,opt,name=kubernetes,proto3" json:"kubernetes,omitempty"`
	Observer      *Observer                     `protobuf:"bytes,16,opt,name=observer,proto3" json:"observer,omitempty"`
	DataStream    *DataStream                   `protobuf:"bytes,17,opt,name=data_stream,json=dataStream,proto3" json:"data_stream,omitempty"`
	Agent         *Agent                        `protobuf:"bytes,18,opt,name=agent,proto3" json:"agent,omitempty"`
	Http          *HTTP                         `protobuf:"bytes,19,opt,name=http,proto3" json:"http,omitempty"`
	UserAgent     *UserAgent                    `protobuf:"bytes,20,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// parent_id holds an optional parent span/transaction ID.
	ParentId string  `protobuf:"bytes,21,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Message  string  `protobuf:"bytes,22,opt,name=message,proto3" json:"message,omitempty"`
	Trace    *Trace  `protobuf:"bytes,23,opt,name=trace,proto3" json:"trace,omitempty"`
	Host     *Host   `protobuf:"bytes,24,opt,name=host,proto3" json:"host,omitempty"`
	Url      *URL    `protobuf:"bytes,25,opt,name=url,proto3" json:"url,omitempty"`
	Log      *Log    `protobuf:"bytes,26,opt,name=log,proto3" json:"log,omitempty"`
	Source   *Source `protobuf:"bytes,27,opt,name=source,proto3" json:"source,omitempty"`
	Client   *Client `protobuf:"bytes,28,opt,name=client,proto3" json:"client,omitempty"`
	// child_ids holds an optional set of child span IDs. This is used for exotic
	// use cases where the parent knows the child ID, but the child does not know
	// the parent ID; namely for profiler-inferred spans.
	ChildIds      []string     `protobuf:"bytes,29,rep,name=child_ids,json=childIds,proto3" json:"child_ids,omitempty"`
	Destination   *Destination `protobuf:"bytes,30,opt,name=destination,proto3" json:"destination,omitempty"`
	Session       *Session     `protobuf:"bytes,31,opt,name=session,proto3" json:"session,omitempty"`
	Process       *Process     `protobuf:"bytes,32,opt,name=process,proto3" json:"process,omitempty"`
	Event         *Event       `protobuf:"bytes,33,opt,name=event,proto3" json:"event,omitempty"`
	Code          *Code        `protobuf:"bytes,34,opt,name=code,proto3" json:"code,omitempty"`
	System        *System      `protobuf:"bytes,35,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APMEvent) Reset() {
	*x = APMEvent{}
	mi := &file_apmevent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APMEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APMEvent) ProtoMessage() {}

func (x *APMEvent) ProtoReflect() protoreflect.Message {
	mi := &file_apmevent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APMEvent.ProtoReflect.Descriptor instead.
func (*APMEvent) Descriptor() ([]byte, []int) {
	return file_apmevent_proto_rawDescGZIP(), []int{0}
}

func (x *APMEvent) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *APMEvent) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *APMEvent) GetNumericLabels() map[string]*NumericLabelValue {
	if x != nil {
		return x.NumericLabels
	}
	return nil
}

func (x *APMEvent) GetLabels() map[string]*LabelValue {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *APMEvent) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *APMEvent) GetMetricset() *Metricset {
	if x != nil {
		return x.Metricset
	}
	return nil
}

func (x *APMEvent) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *APMEvent) GetCloud() *Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *APMEvent) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *APMEvent) GetFaas() *Faas {
	if x != nil {
		return x.Faas
	}
	return nil
}

func (x *APMEvent) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *APMEvent) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *APMEvent) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *APMEvent) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *APMEvent) GetKubernetes() *Kubernetes {
	if x != nil {
		return x.Kubernetes
	}
	return nil
}

func (x *APMEvent) GetObserver() *Observer {
	if x != nil {
		return x.Observer
	}
	return nil
}

func (x *APMEvent) GetDataStream() *DataStream {
	if x != nil {
		return x.DataStream
	}
	return nil
}

func (x *APMEvent) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *APMEvent) GetHttp() *HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *APMEvent) GetUserAgent() *UserAgent {
	if x != nil {
		return x.UserAgent
	}
	return nil
}

func (x *APMEvent) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *APMEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APMEvent) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *APMEvent) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *APMEvent) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *APMEvent) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *APMEvent) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *APMEvent) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *APMEvent) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

func (x *APMEvent) GetDestination() *Destination {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *APMEvent) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *APMEvent) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *APMEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *APMEvent) GetCode() *Code {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *APMEvent) GetSystem() *System {
	if x != nil {
		return x.System
	}
	return nil
}

var File_apmevent_proto protoreflect.FileDescriptor

const file_apmevent_proto_rawDesc = "" +
	"\n" +
	"\x0eapmevent.proto\x12\x0eelastic.apm.v1\x1a\vagent.proto\x1a\fclient.proto\x1a\vcloud.proto\x1a\n" +
	"code.proto\x1a\x0fcontainer.proto\x1a\x10datastream.proto\x1a\x11destination.proto\x1a\fdevice.proto\x1a\verror.proto\x1a\vevent.proto\x1a\n" +
	"faas.proto\x1a\n" +
	"host.proto\x1a\n" +
	"http.proto\x1a\x10kubernetes.proto\x1a\flabels.proto\x1a\tlog.proto\x1a\x0fmetricset.proto\x1a\rnetwork.proto\x1a\x0eobserver.proto\x1a\rprocess.proto\x1a\rservice.proto\x1a\rsession.proto\x1a\fsource.proto\x1a\n" +
	"span.proto\x1a\fsystem.proto\x1a\vtrace.proto\x1a\x11transaction.proto\x1a\turl.proto\x1a\n" +
	"user.proto\x1a\x0fuseragent.proto\"\xda\x0e\n" +
	"\bAPMEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12(\n" +
	"\x04span\x18\x02 \x01(\v2\x14.elastic.apm.v1.SpanR\x04span\x12R\n" +
	"\x0enumeric_labels\x18\x03 \x03(\v2+.elastic.apm.v1.APMEvent.NumericLabelsEntryR\rnumericLabels\x12<\n" +
	"\x06labels\x18\x04 \x03(\v2$.elastic.apm.v1.APMEvent.LabelsEntryR\x06labels\x12=\n" +
	"\vtransaction\x18\x05 \x01(\v2\x1b.elastic.apm.v1.TransactionR\vtransaction\x127\n" +
	"\tmetricset\x18\x06 \x01(\v2\x19.elastic.apm.v1.MetricsetR\tmetricset\x12+\n" +
	"\x05error\x18\a \x01(\v2\x15.elastic.apm.v1.ErrorR\x05error\x12+\n" +
	"\x05cloud\x18\b \x01(\v2\x15.elastic.apm.v1.CloudR\x05cloud\x121\n" +
	"\aservice\x18\t \x01(\v2\x17.elastic.apm.v1.ServiceR\aservice\x12(\n" +
	"\x04faas\x18\n" +
	" \x01(\v2\x14.elastic.apm.v1.FaasR\x04faas\x121\n" +
	"\anetwork\x18\v \x01(\v2\x17.elastic.apm.v1.NetworkR\anetwork\x127\n" +
	"\tcontainer\x18\f \x01(\v2\x19.elastic.apm.v1.ContainerR\tcontainer\x12(\n" +
	"\x04user\x18\r \x01(\v2\x14.elastic.apm.v1.UserR\x04user\x12.\n" +
	"\x06device\x18\x0e \x01(\v2\x16.elastic.apm.v1.DeviceR\x06device\x12:\n" +
	"\n" +
	"kubernetes\x18\x0f \x01(\v2\x1a.elastic.apm.v1.KubernetesR\n" +
	"kubernetes\x124\n" +
	"\bobserver\x18\x10 \x01(\v2\x18.elastic.apm.v1.ObserverR\bobserver\x12;\n" +
	"\vdata_stream\x18\x11 \x01(\v2\x1a.elastic.apm.v1.DataStreamR\n" +
	"dataStream\x12+\n" +
	"\x05agent\x18\x12 \x01(\v2\x15.elastic.apm.v1.AgentR\x05agent\x12(\n" +
	"\x04http\x18\x13 \x01(\v2\x14.elastic.apm.v1.HTTPR\x04http\x128\n" +
	"\n" +
	"user_agent\x18\x14 \x01(\v2\x19.elastic.apm.v1.UserAgentR\tuserAgent\x12\x1b\n" +
	"\tparent_id\x18\x15 \x01(\tR\bparentId\x12\x18\n" +
	"\amessage\x18\x16 \x01(\tR\amessage\x12+\n" +
	"\x05trace\x18\x17 \x01(\v2\x15.elastic.apm.v1.TraceR\x05trace\x12(\n" +
	"\x04host\x18\x18 \x01(\v2\x14.elastic.apm.v1.HostR\x04host\x12%\n" +
	"\x03url\x18\x19 \x01(\v2\x13.elastic.apm.v1.URLR\x03url\x12%\n" +
	"\x03log\x18\x1a \x01(\v2\x13.elastic.apm.v1.LogR\x03log\x12.\n" +
	"\x06source\x18\x1b \x01(\v2\x16.elastic.apm.v1.SourceR\x06source\x12.\n" +
	"\x06client\x18\x1c \x01(\v2\x16.elastic.apm.v1.ClientR\x06client\x12\x1b\n" +
	"\tchild_ids\x18\x1d \x03(\tR\bchildIds\x12=\n" +
	"\vdestination\x18\x1e \x01(\v2\x1b.elastic.apm.v1.DestinationR\vdestination\x121\n" +
	"\asession\x18\x1f \x01(\v2\x17.elastic.apm.v1.SessionR\asession\x121\n" +
	"\aprocess\x18  \x01(\v2\x17.elastic.apm.v1.ProcessR\aprocess\x12+\n" +
	"\x05event\x18! \x01(\v2\x15.elastic.apm.v1.EventR\x05event\x12(\n" +
	"\x04code\x18\" \x01(\v2\x14.elastic.apm.v1.CodeR\x04code\x12.\n" +
	"\x06system\x18# \x01(\v2\x16.elastic.apm.v1.SystemR\x06system\x1ac\n" +
	"\x12NumericLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.elastic.apm.v1.NumericLabelValueR\x05value:\x028\x01\x1aU\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.elastic.apm.v1.LabelValueR\x05value:\x028\x01B+Z)github.com/elastic/apm-data/model/modelpbb\x06proto3"

var (
	file_apmevent_proto_rawDescOnce sync.Once
	file_apmevent_proto_rawDescData []byte
)

func file_apmevent_proto_rawDescGZIP() []byte {
	file_apmevent_proto_rawDescOnce.Do(func() {
		file_apmevent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apmevent_proto_rawDesc), len(file_apmevent_proto_rawDesc)))
	})
	return file_apmevent_proto_rawDescData
}

var file_apmevent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apmevent_proto_goTypes = []any{
	(*APMEvent)(nil),          // 0: elastic.apm.v1.APMEvent
	nil,                       // 1: elastic.apm.v1.APMEvent.NumericLabelsEntry
	nil,                       // 2: elastic.apm.v1.APMEvent.LabelsEntry
	(*Span)(nil),              // 3: elastic.apm.v1.Span
	(*Transaction)(nil),       // 4: elastic.apm.v1.Transaction
	(*Metricset)(nil),         // 5: elastic.apm.v1.Metricset
	(*Error)(nil),             // 6: elastic.apm.v1.Error
	(*Cloud)(nil),             // 7: elastic.apm.v1.Cloud
	(*Service)(nil),           // 8: elastic.apm.v1.Service
	(*Faas)(nil),              // 9: elastic.apm.v1.Faas
	(*Network)(nil),           // 10: elastic.apm.v1.Network
	(*Container)(nil),         // 11: elastic.apm.v1.Container
	(*User)(nil),              // 12: elastic.apm.v1.User
	(*Device)(nil),            // 13: elastic.apm.v1.Device
	(*Kubernetes)(nil),        // 14: elastic.apm.v1.Kubernetes
	(*Observer)(nil),          // 15: elastic.apm.v1.Observer
	(*DataStream)(nil),        // 16: elastic.apm.v1.DataStream
	(*Agent)(nil),             // 17: elastic.apm.v1.Agent
	(*HTTP)(nil),              // 18: elastic.apm.v1.HTTP
	(*UserAgent)(nil),         // 19: elastic.apm.v1.UserAgent
	(*Trace)(nil),             // 20: elastic.apm.v1.Trace
	(*Host)(nil),              // 21: elastic.apm.v1.Host
	(*URL)(nil),               // 22: elastic.apm.v1.URL
	(*Log)(nil),               // 23: elastic.apm.v1.Log
	(*Source)(nil),            // 24: elastic.apm.v1.Source
	(*Client)(nil),            // 25: elastic.apm.v1.Client
	(*Destination)(nil),       // 26: elastic.apm.v1.Destination
	(*Session)(nil),           // 27: elastic.apm.v1.Session
	(*Process)(nil),           // 28: elastic.apm.v1.Process
	(*Event)(nil),             // 29: elastic.apm.v1.Event
	(*Code)(nil),              // 30: elastic.apm.v1.Code
	(*System)(nil),            // 31: elastic.apm.v1.System
	(*NumericLabelValue)(nil), // 32: elastic.apm.v1.NumericLabelValue
	(*LabelValue)(nil),        // 33: elastic.apm.v1.LabelValue
}
var file_apmevent_proto_depIdxs = []int32{
	3,  // 0: elastic.apm.v1.APMEvent.span:type_name -> elastic.apm.v1.Span
	1,  // 1: elastic.apm.v1.APMEvent.numeric_labels:type_name -> elastic.apm.v1.APMEvent.NumericLabelsEntry
	2,  // 2: elastic.apm.v1.APMEvent.labels:type_name -> elastic.apm.v1.APMEvent.LabelsEntry
	4,  // 3: elastic.apm.v1.APMEvent.transaction:type_name -> elastic.apm.v1.Transaction
	5,  // 4: elastic.apm.v1.APMEvent.metricset:type_name -> elastic.apm.v1.Metricset
	6,  // 5: elastic.apm.v1.APMEvent.error:type_name -> elastic.apm.v1.Error
	7,  // 6: elastic.apm.v1.APMEvent.cloud:type_name -> elastic.apm.v1.Cloud
	8,  // 7: elastic.apm.v1.APMEvent.service:type_name -> elastic.apm.v1.Service
	9,  // 8: elastic.apm.v1.APMEvent.faas:type_name -> elastic.apm.v1.Faas
	10, // 9: elastic.apm.v1.APMEvent.network:type_name -> elastic.apm.v1.Network
	11, // 10: elastic.apm.v1.APMEvent.container:type_name -> elastic.apm.v1.Container
	12, // 11: elastic.apm.v1.APMEvent.user:type_name -> elastic.apm.v1.User
	13, // 12: elastic.apm.v1.APMEvent.device:type_name -> elastic.apm.v1.Device
	14, // 13: elastic.apm.v1.APMEvent.kubernetes:type_name -> elastic.apm.v1.Kubernetes
	15, // 14: elastic.apm.v1.APMEvent.observer:type_name -> elastic.apm.v1.Observer
	16, // 15: elastic.apm.v1.APMEvent.data_stream:type_name -> elastic.apm.v1.DataStream
	17, // 16: elastic.apm.v1.APMEvent.agent:type_name -> elastic.apm.v1.Agent
	18, // 17: elastic.apm.v1.APMEvent.http:type_name -> elastic.apm.v1.HTTP
	19, // 18: elastic.apm.v1.APMEvent.user_agent:type_name -> elastic.apm.v1.UserAgent
	20, // 19: elastic.apm.v1.APMEvent.trace:type_name -> elastic.apm.v1.Trace
	21, // 20: elastic.apm.v1.APMEvent.host:type_name -> elastic.apm.v1.Host
	22, // 21: elastic.apm.v1.APMEvent.url:type_name -> elastic.apm.v1.URL
	23, // 22: elastic.apm.v1.APMEvent.log:type_name -> elastic.apm.v1.Log
	24, // 23: elastic.apm.v1.APMEvent.source:type_name -> elastic.apm.v1.Source
	25, // 24: elastic.apm.v1.APMEvent.client:type_name -> elastic.apm.v1.Client
	26, // 25: elastic.apm.v1.APMEvent.destination:type_name -> elastic.apm.v1.Destination
	27, // 26: elastic.apm.v1.APMEvent.session:type_name -> elastic.apm.v1.Session
	28, // 27: elastic.apm.v1.APMEvent.process:type_name -> elastic.apm.v1.Process
	29, // 28: elastic.apm.v1.APMEvent.event:type_name -> elastic.apm.v1.Event
	30, // 29: elastic.apm.v1.APMEvent.code:type_name -> elastic.apm.v1.Code
	31, // 30: elastic.apm.v1.APMEvent.system:type_name -> elastic.apm.v1.System
	32, // 31: elastic.apm.v1.APMEvent.NumericLabelsEntry.value:type_name -> elastic.apm.v1.NumericLabelValue
	33, // 32: elastic.apm.v1.APMEvent.LabelsEntry.value:type_name -> elastic.apm.v1.LabelValue
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_apmevent_proto_init() }
func file_apmevent_proto_init() {
	if File_apmevent_proto != nil {
		return
	}
	file_agent_proto_init()
	file_client_proto_init()
	file_cloud_proto_init()
	file_code_proto_init()
	file_container_proto_init()
	file_datastream_proto_init()
	file_destination_proto_init()
	file_device_proto_init()
	file_error_proto_init()
	file_event_proto_init()
	file_faas_proto_init()
	file_host_proto_init()
	file_http_proto_init()
	file_kubernetes_proto_init()
	file_labels_proto_init()
	file_log_proto_init()
	file_metricset_proto_init()
	file_network_proto_init()
	file_observer_proto_init()
	file_process_proto_init()
	file_service_proto_init()
	file_session_proto_init()
	file_source_proto_init()
	file_span_proto_init()
	file_system_proto_init()
	file_trace_proto_init()
	file_transaction_proto_init()
	file_url_proto_init()
	file_user_proto_init()
	file_useragent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apmevent_proto_rawDesc), len(file_apmevent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apmevent_proto_goTypes,
		DependencyIndexes: file_apmevent_proto_depIdxs,
		MessageInfos:      file_apmevent_proto_msgTypes,
	}.Build()
	File_apmevent_proto = out.File
	file_apmevent_proto_goTypes = nil
	file_apmevent_proto_depIdxs = nil
}
