// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: kubernetes.proto

package modelpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kubernetes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid        string                 `protobuf:"bytes,4,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kubernetes) Reset() {
	*x = Kubernetes{}
	mi := &file_kubernetes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kubernetes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes) ProtoMessage() {}

func (x *Kubernetes) ProtoReflect() protoreflect.Message {
	mi := &file_kubernetes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes.ProtoReflect.Descriptor instead.
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return file_kubernetes_proto_rawDescGZIP(), []int{0}
}

func (x *Kubernetes) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Kubernetes) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Kubernetes) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Kubernetes) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

var File_kubernetes_proto protoreflect.FileDescriptor

const file_kubernetes_proto_rawDesc = "" +
	"\n" +
	"\x10kubernetes.proto\x12\x0eelastic.apm.v1\"{\n" +
	"\n" +
	"Kubernetes\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\x04 \x01(\tR\x06podUidB+Z)github.com/elastic/apm-data/model/modelpbb\x06proto3"

var (
	file_kubernetes_proto_rawDescOnce sync.Once
	file_kubernetes_proto_rawDescData []byte
)

func file_kubernetes_proto_rawDescGZIP() []byte {
	file_kubernetes_proto_rawDescOnce.Do(func() {
		file_kubernetes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubernetes_proto_rawDesc), len(file_kubernetes_proto_rawDesc)))
	})
	return file_kubernetes_proto_rawDescData
}

var file_kubernetes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kubernetes_proto_goTypes = []any{
	(*Kubernetes)(nil), // 0: elastic.apm.v1.Kubernetes
}
var file_kubernetes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kubernetes_proto_init() }
func file_kubernetes_proto_init() {
	if File_kubernetes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubernetes_proto_rawDesc), len(file_kubernetes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kubernetes_proto_goTypes,
		DependencyIndexes: file_kubernetes_proto_depIdxs,
		MessageInfos:      file_kubernetes_proto_msgTypes,
	}.Build()
	File_kubernetes_proto = out.File
	file_kubernetes_proto_goTypes = nil
	file_kubernetes_proto_depIdxs = nil
}
