// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: labels.proto

package modelpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabelValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Global        bool                   `protobuf:"varint,3,opt,name=global,proto3" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelValue) Reset() {
	*x = LabelValue{}
	mi := &file_labels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelValue) ProtoMessage() {}

func (x *LabelValue) ProtoReflect() protoreflect.Message {
	mi := &file_labels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelValue.ProtoReflect.Descriptor instead.
func (*LabelValue) Descriptor() ([]byte, []int) {
	return file_labels_proto_rawDescGZIP(), []int{0}
}

func (x *LabelValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LabelValue) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *LabelValue) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

type NumericLabelValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Global        bool                   `protobuf:"varint,3,opt,name=global,proto3" json:"global,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericLabelValue) Reset() {
	*x = NumericLabelValue{}
	mi := &file_labels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericLabelValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericLabelValue) ProtoMessage() {}

func (x *NumericLabelValue) ProtoReflect() protoreflect.Message {
	mi := &file_labels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericLabelValue.ProtoReflect.Descriptor instead.
func (*NumericLabelValue) Descriptor() ([]byte, []int) {
	return file_labels_proto_rawDescGZIP(), []int{1}
}

func (x *NumericLabelValue) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *NumericLabelValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *NumericLabelValue) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

var File_labels_proto protoreflect.FileDescriptor

const file_labels_proto_rawDesc = "" +
	"\n" +
	"\flabels.proto\x12\x0eelastic.apm.v1\"R\n" +
	"\n" +
	"LabelValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\x12\x16\n" +
	"\x06global\x18\x03 \x01(\bR\x06global\"Y\n" +
	"\x11NumericLabelValue\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x16\n" +
	"\x06global\x18\x03 \x01(\bR\x06globalB+Z)github.com/elastic/apm-data/model/modelpbb\x06proto3"

var (
	file_labels_proto_rawDescOnce sync.Once
	file_labels_proto_rawDescData []byte
)

func file_labels_proto_rawDescGZIP() []byte {
	file_labels_proto_rawDescOnce.Do(func() {
		file_labels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_labels_proto_rawDesc), len(file_labels_proto_rawDesc)))
	})
	return file_labels_proto_rawDescData
}

var file_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_labels_proto_goTypes = []any{
	(*LabelValue)(nil),        // 0: elastic.apm.v1.LabelValue
	(*NumericLabelValue)(nil), // 1: elastic.apm.v1.NumericLabelValue
}
var file_labels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_labels_proto_init() }
func file_labels_proto_init() {
	if File_labels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_labels_proto_rawDesc), len(file_labels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_labels_proto_goTypes,
		DependencyIndexes: file_labels_proto_depIdxs,
		MessageInfos:      file_labels_proto_msgTypes,
	}.Build()
	File_labels_proto = out.File
	file_labels_proto_goTypes = nil
	file_labels_proto_depIdxs = nil
}
